name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install -g @bubblewrap/cli

      - name: Restore keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > echoworld.jks

      - name: Init TWA
        run: |
          npx bubblewrap init \
          --manifest=https://echo-world-rho.vercel.app/manifest.json

      - name: Build AAB
        run: |
          npx bubblewrap build

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: echoworld-aab
          path: app-release-bundle.aab
